### ISSUE TITLE
Automatically check for duplicates on submission or admin add

### ISSUE THREAD

**Issue by alkemann** [alkemann/stone_soup_cosplay#12]
When duplicates are found, make sure to:

1. Mark neither as "accepted", forcing moderation?
2. Compare scores and mark the highest one that has a score value as "HS"

**Comment by RoGGa-loves-DCSS** [comment]
there's 3 scenarios that I can see: 
1. players enters 2 runs: moderation required even if 1 was "Accepted";
2. admin enters 2 runs: no moderation if 1st one no longer has HS
3. each enters 1: Moderation required
