### ISSUE TITLE
Add field for Unique's in-game description

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#13]
for Khufu it is:
"An incredibly powerful emperor on the way to godhood. He died quite some time ago, but he sees no reason why that should stop him."

For Bai:
"A weary draconian with foreign and watery scales. She has come to the Dungeon in hopes of resurrecting her mortal husband; a noble cause, for a being once known for quarreling with saints and flooding unfortunate temples. If pressed to her limits, she will reveal her true form, the mere sight of which struck her husband dead. Adventurers may wish they were so lucky!"

**Comment by alkemann** [comment]
Added the feature, now go add the descriptions @RoGGa-loves-DCSS  :)

**Comment by RoGGa-loves-DCSS** [comment]
Set 2, 3 & 4 done

Set 1 will likely get done at the same time as data entry for points, conducts and bonuses.
