### ISSUE TITLE
Crawl footsteps as visual <hr>

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#14]
https://cdn.discordapp.com/attachments/558269304852709393/562072833883242526/horizontal_steps-left_and_right.png

**Comment by RoGGa-loves-DCSS** [comment]
https://cdn.discordapp.com/attachments/558269304852709393/562494292845920256/horizontal_steps-heading_left.png

https://cdn.discordapp.com/attachments/558269304852709393/562494300697395220/horizontal_steps-heading_right.png

**Comment by kitchen-ace** [comment]
I'm going to close this as "no" for now; I'll keep it in mind when I start working on the css though.
