### ISSUE TITLE
Breakdown scores/stars into individual points

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#21]
It might be nice if, instead of entering a score and star total, there were a bunch of checkboxes or similar for each milestone/conduct/bonus challenge, and an overall score was calculated from what was checked. 

For compatibility the manually-entered score should probably be kept; there's no need to break down already entered challenges.

**Comment by kitchen-ace** [comment]
This could also be extended so that players submitting their own morgues can check the appropriate boxes and then an admin can just review it, check/uncheck anything as appropriate, and then approve it.

**Comment by alkemann** [comment]
Checkboxes for milestone and conducts on submit and points on admin?

I was thinking stars could be a radio button with 0, 1, 2 since that would be a lot faster than typing.

**Comment by kitchen-ace** [comment]
I think that will do it. Thanks!
