### ISSUE TITLE
"Special Rule" field

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#29]
Occasionally I will want to have some deviation from the rules, like allowing an old version or letting the player switch gods. This should probably appear before the Cosplay Conduct Points header, with its own attention-getting header (coloured text?), but only when the special rule field is filled out. Alternately just having a general purpose field that appears there, where I can enter html, would be fine.

**Comment by alkemann** [comment]
having html in the db can quickly become a risk. adding a text field for optional special rule that will be presented in a highlighted fashion is a trivial feature to add, so if that is the need we are solving, I suggest we go with the "special rule" option

**Comment by kitchen-ace** [comment]
Just fine with me.

**Comment by alkemann** [comment]
Added a field for special rule to challenges. Displayed in red, if present, on the home page and on the detailed page and listed also in the admin challenges list.

Please go ahead an add a special rule to the current challenge to test @kitchen-ace

**Comment by kitchen-ace** [comment]
Looks good except a long special rule doesn't get any line break in http://www.crawlcosplay.com/challenges/list (log in as admin). The rule doesn't even need to be on that page, or maybe just a note that a special rule exists is enough.

**Comment by alkemann** [comment]
Ill remove it
