### ISSUE TITLE
Allow paragraphs in descriptions fields.

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#31]
Descriptions for some challenges etc. sometimes benefit from multiple paragraphs, or even bullets. See the first challenge in http://dcsscosplay.herokuapp.com/challenges/details?id=51 vs https://www.reddit.com/r/dcss/comments/alzylu/crawl_cosplay_challenge_set_3_week_3_grum_the/

For the Set 4 challenges I went and added some html to the descriptions where needed. However you said in another comment that "having html in the db can quickly become a risk" so I gather that's not the best solution. (I can undo that immediately if you think it is best to do so.) 

Other basic formatting (bullets, italics, etc.) would be *nice* but are considerably less important than separate paragraphs.

**Comment by kitchen-ace** [comment]
I've gone and removed all the html, since legibility doesn't matter much at this point while the site is not public. You can see the obvious need for paragraphs in the second bonus challenge for Psyche:

http://dcsscosplay.herokuapp.com/challenges/details?id=1

**Comment by alkemann** [comment]
At the moment we don't have any protection on the output of the db, but ideally we would escape any html put in there so that malicious users would not be able to add bad html (like javascript) there. 

We could have an exception for the challenges since those are only editable by you.

**Comment by alkemann** [comment]
maybe we could use a similar system to github and reddit? Are you familiar with markdown?

**Comment by kitchen-ace** [comment]
Sure am (can't you tell from the reddit posts? :p), if it's easy to integrate. Paragraphs are all that are *really* important though.

**Comment by alkemann** [comment]
Ah right. Didn't think about that 😊

**Comment by alkemann** [comment]
Hey. I added escaping of html chars to all the public pages, and at the same time added markdown support (but escapes html) to the following fields (to be used on home and details pages): 

 - Special rule
 - Conducts
 - Bonuses

**Comment by kitchen-ace** [comment]
Wonderful! Leaving this open until I actually update all the currently posted challenges. 

edit: done!
