### ISSUE TITLE
Add an "about" page

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#33]
For general ccc info, credits, etc. I can probably do this if you want alkemann, but I'm not going to try it tonight, so maybe you'll beat me to it. I will fill the text out either way.

**Comment by alkemann** [comment]
Pages are added by just adding files in the content folder. Added a placeholder for you in a dedicated branch: https://github.com/alkemann/stone_soup_cosplay/blob/about-page/content/pages/about.html.php

**Comment by kitchen-ace** [comment]
Made a first draft, might need some revision.

There's a credits section, if @alkemann or @RoGGa-loves-DCSS want a link on your name there, let me know.

**Comment by alkemann** [comment]
where do we put the link to it? top menu?

**Comment by kitchen-ace** [comment]
Yeah, between "home" and "history" i think?
