### ISSUE TITLE
Free vs. paid hosting

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#34]
I'm adding this as an issue here just so we can talk about it a little more easily than through messages on discord, which isn't great for longer discussions. (And because I'm wordy...) If someone would prefer to move it somewhere more private, that's fine, just let me know.

Without going in to detail, my income is going to be extremely variable and unpredictable for the foreseeable future, and I really don't have the funds to commit to any kind of regular web hosting. Paying for a domain name is fine, but I don't want to go beyond that unless it is similarly inexpensive. (~$10 a year.) When I was planning for my own website/score tracking, I was counting on using free hosting. (From freewha.com as it seemed to be the best option I found - it also has a $12/year paid option, which is cheap enough for me to manage, if it were beneficial to do so.)

I would also feel *extremely* uncomfortable soliciting donations from cosplay participants. While I'm sure a few people would be happy to contribute (and I know alkemann offered), I feel that asking for financial assistance in running it, even if none of it is actually going in my pocket, would change the atmosphere of the whole thing in a direction I don't want. I'm not sure how to articulate this better, but it's something I've felt when similar endeavours in other communities have begun asking for donations, and not because I am opposed to contributing towards such a thing myself. It's just that having some financial pressure to keep the cosplay challenge running is a strong negative to me.

I am extremely impressed with, and grateful for, the work you (alkemann) have done on this website, so please don't take this next statement as being dismissive of your efforts: the cosplay challenge ultimately does not need a website, and could continue to run just fine, for free, on reddit alone. 

So with all of that said, what do we (or you in particular) lose out on by not having a paid heroku account, or other paid hosting? Is there a better free/very-low-cost option than a free heroku account? I'm still not 100% clear on all the benefits that heroku provides, probably just because I'm not an actual web developer; not to say that you need to fully explain it to me, I just can't make accurate comparisons to other platforms/hosting/etc.

**Comment by RoGGa-loves-DCSS** [comment]
floraline might be open to hosting it.
crawlcosplay.kelbi.org

**Comment by alkemann** [comment]
I am very sceptical of a freehosting service.. As they say, if you are not paying, you are the product. I took a quick look at freewha.com and it seems to cover the base needs we have. I can maybe try to put up a copy of the site there sometime in the near future to give it a test. 

The features that is provided by Heroku that is making this better for me, we are already getting with the free version, but we won't get with a place like freewha.com (as far as i know), are mostly the automation (automatic deploy changes in a safe and fast way).

The reason to go for he paid reasons are scaling to a larger audience (probably not an issue we will have, but the site does go to sleep and needs a longer response time first request after a while) and significantly, a database larger that 5 MB. This last point is my concern, but maybe we won't really get enough submissions for that to be a problem. At least for a while.

I have an alternative suggestion as a compromise: we host the public/production site on freewha.com (or similar) where updates will be more difficult, but we do more seldom. And we keep using the Heroku one for all our development testing (where updated are easy and instant).

**Comment by RoGGa-loves-DCSS** [comment]
very good solution proposal.
how big is the database right now?

**Comment by kitchen-ace** [comment]
Also, as I said in a message to alkemann, I'm open to *some* amount of outside contribution. My main problem in that regard is that I don't want a perpetual "donate" on the site, or for people to think that if they don't contribute, the cosplay challenge might shut down.

Speaking of which, floraline has now added a donation link to CKO.

I'm willing to up my personal contribution budget to $25 US. What kind of plans are available for Heroku that might be worth getting? Getting 6 months of a premium Heroku account while the site is still in heavy development might be worth it; afterwards we can possibly switch to a cheaper host, cheaper plan, or attempt a bit of fundraising.

**Comment by alkemann** [comment]
The database atm is around 100kb now. But for example we can not add a feature to store morgues in the database without very quickly going out of space. At present data model, we should be able to go for quite a while I think.

**Comment by alkemann** [comment]
lets close this for now and take it back up again if it becomes an issue
