### ISSUE TITLE
short form or punctuation for race/bg/god on main page

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#35]
The main page lists the applicable species, background, and god options for each challenge, in parentheses. But without any punctuation it can look confusing when some of those options have multiple choices. For example: (Minotaur Fighter or Skald Makhleb) sounds quite strange if you try to parse it as plain english. Possible solutions:

1) add commas, so you get e.g. "Minotaur, Fighter or Skald, Makhleb"

2) add a "short form" field so I can enter "Mi Fi/Sk Mak" and have that display in parentheses instead.

unnecessary: Automatically generate a short-form display from the full species/bg/god fields. Too much work.

**Comment by alkemann** [comment]
Added commas. will work as fallback where shortform field is not filled out

**Comment by alkemann** [comment]
Shortform field added in fed21ec9b058016197861ac6b0c03fde48501a67

**Comment by alkemann** [comment]
Up to you to add shortform where it would be nicer, comma of full will be used where the shortform field is not filled.

**Comment by kitchen-ace** [comment]
Thanks! I think commas are fine, there's enough room to have things fully spelled out that way.

**Comment by kitchen-ace** [comment]
Reopening because the fallback isn't working with Asterion right now. Though I don't really mind having to fill that field in.

**Comment by alkemann** [comment]
yes it gets broken when you first fill inn shortform then remove it. easy fix

**Comment by kitchen-ace** [comment]
Thanks! I prefer the look of full words with commas for the way the page is laid out, however on occasion I might make use of the shortform field for something (like the current challenge where "none" isn't required and looks odd with two sets of parentheses.
