### ISSUE TITLE
recent submissions page

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#36]
Basically like http://www.crawlcosplay.com/submissions/list when logged in, except for public viewing. The idea being that, in theory, people could submit entries for past challenges. I don't know if anyone will bother or not. 

To go along with that, I guess some sort of "late entry" flag for submissions?

Probably not that difficult to implement but also not a priority so I'm giving it the "future" milestone.

**Comment by alkemann** [comment]
So should this page also list submissions without the accepted flag? Without the highscore flag?

**Comment by alkemann** [comment]
Added one that is similar to the one we had for admin, listing approved ones only, irregardless of if they are highscore or not. Close ticket if that works or comment with changes

**Comment by kitchen-ace** [comment]
Looks good, thanks!
