### ISSUE TITLE
An admin page for each player and their submissions

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#4]
FR: I would like an admin page for each player and their submissions: "Player's submissions" ordered by Set#&Week#.
That way I could find any double entries myself.

This would be very beneficial since there is the likelihood that someone will: 
(1) post their Morgue url on Reddit, and (2) submit a run on CCC website 
So whoever enters the data might enter what is on Reddit even though it is already submitted and waiting approval

**Comment by alkemann** [comment]
Ok or need more sorting?

**Comment by RoGGa-loves-DCSS** [comment]
order by set&week
