### ISSUE TITLE
add deadline to the week's challenge on homepage (Friday Noon GMT)

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#40]

**Comment by alkemann** [comment]
is that always the deadline @kitchen-ace ?

**Comment by RoGGa-loves-DCSS** [comment]
it has been since Set1 week1
see: https://www.reddit.com/r/dcss/comments/a1pslv/crawl_cosplay_challenge_set_2_week_15_polyphemus/

**Comment by kitchen-ace** [comment]
It has always been the "official" deadline. In practice I am not especially strict about late entries, so I'm not sure what to say about adding the time, or how to phrase it, etc.

**Comment by alkemann** [comment]
This got added in an earlier commit
