### ISSUE TITLE
"Late Entry" flag for entries well past the deadline

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#42]
(Don't do anything with this quite yet, I'm mostly brainstorming/writing down ideas so I don't forget them later.)

One idea I have with this website is that people can submit entries for challenges long-past, e.g. I have a Mennas win (set 1) done within the past few months because it's one of the few I missed entirely. It would be nice if these still got included on the player page, but I think they shouldn't count towards a set's score total.

Thus, a submission with the "late entry" flag should still appear on the set scoreboard, but not count for the total, and should maybe be italicized or formatted differently. (Strikethrough might work?)

**Comment by alkemann** [comment]
If we add a submit button to all detail pages, we need this to capture late entries right?

**Comment by kitchen-ace** [comment]
Yeah, though it *shouldn't* be flagged automatically. There are often not-very-late entries for the previous challenge once the new one starts. 

edit: I meant SHOULDN'T be flagged automatically

**Comment by alkemann** [comment]
i'll add the option to flag an entry as late, but I think it will actually work to use the "high score" field as well to not include the entry in official scoring. in other words, we allow multiple and late entries, and can who them on the player page, but only the "high score" (or now "scoring") entry counts.

So you can mark an entry as "late, accepted, not-high score"
