### ISSUE TITLE
"submit" link on challenge details page, esp. for old challenges

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#43]
Since I want people to be able to submit runs for old challenges (and especially since I treat deadlines as more of a suggestion than a hard cutoff) I think there should be a submit link on the details page for all challenges. This is also a good idea even for the current challenge, because it is potentially confusing that you can look at a challenge but can't submit a run without going back to the main page.

**Comment by alkemann** [comment]
easy add on active challenge details, should we add it on the others prior to having the "late entry" flag?

**Comment by alkemann** [comment]
I added the "late" flag in #42 but it isn't the field that is used for calculating if the submission is scoring or not, that is the "high score" (maybe rename it to "scoring") field. So we could automatically flag entries that are on the non-active challenge as late and have it be up to moderator if it gets flagged as scoring or not. Also can remove the late flag too if wanted.
