### ISSUE TITLE
Flag challenge as "bonus week", don't count it in score totals

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#46]
Set 2 week 6 is a bonus that I was treating more as a one-off than something that was part of that set, so I'd rather it didn't count in the set total. I'm likely to do other bonus weeks as well at times.

**Comment by alkemann** [comment]
Make it a different set? What is the distinction of a bonus? Count against what?

**Comment by kitchen-ace** [comment]
If you keep it in that set, but just don't add the scores from that week to the total, that would be fine.

Here's how I did it in the reddit thread: https://www.reddit.com/r/dcss/comments/aerja8/crawl_cosplay_challenge_bonus_week_1_joseph_a/

Separating the column off of the rest isn't necessary though, though I guess some visual separator would be nice.

**Comment by kitchen-ace** [comment]
Example mock-up. (I scratched out the scores I didn't change).

There will never be more than one bonus week per set if that helps at all.

![Screenshot_2019-04-15_18-47-56](https://user-images.githubusercontent.com/47063032/56170942-6e8b8c00-5fb1-11e9-9171-c9cfbebc54a0.png)
