### ISSUE TITLE
Extra text for Set 1 overview

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#47]
I'd like this text to appear on http://www.crawlcosplay.com/sets/score?set=1. It can be hard-coded, I don't imagine I'll need a thing like this on any other set overview.

>The Cosplay Challenge was originally run as a continuous series, before the concept of dividing it into sets was introduced. The initial challenges are all grouped as "Set 1."
>
> The scoring system was different, with a perfect score being 70 points. The totals have been adjusted here so that players wishing to try these challenges can submit runs using the current scoring scheme. See the [reddit thread](https://www.reddit.com/r/dcss/comments/9rlseu/casual_cosplay_challenge_week_15_boris_mucj_plus/) for week 15 for the original score totals.

**Comment by alkemann** [comment]
👍
