### ISSUE TITLE
Announcement capability

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#50]
During CSDC and tournaments, we'll need a way to announce on the homepage that the CCC is not currently happening due to those events.

This mean that there will also be no "active" challenge.

**Comment by RoGGa-loves-DCSS** [comment]
The announcement capability could also be useful when there is an active challenge.

**Comment by alkemann** [comment]
What are you suggestion exactly? What is an announcement? The homepage changes when there are no active challenges to display a message to that effect. See lines 91-92 https://github.com/alkemann/stone_soup_cosplay/blob/master/content/pages/home.html.php#L92

**Comment by kitchen-ace** [comment]
I think a message that shows that there are no active challenges is enough. I imagine there will be few people who enter the CCC and are not at least aware of CSDC. I should post a comment in the current challenge thread on reddit at least, though.
