### ISSUE TITLE
Player's scoreboard: sets*weeks

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#51]
In the About page, it states: "the Challenge is about personal achievement rather than competition."...so the player's page should show a grid with, let's say, the following format:

                          WEEKS
    SETS     TOTAL   1  2  3  4  5
    Set 1a
    Set 1b
    Set 1c
    Set 2
    Set 3
    Set 4
    Set 5

**Comment by alkemann** [comment]
I don't really understand what the suggestion is here? Maybe you could clarify what and why?

**Comment by kitchen-ace** [comment]
I think RoGGa is suggesting changing player pages, e.g. http://www.crawlcosplay.com/player?id=71, to a grid/scoreboard that gives an easy overview of every single challenge, with that player's scores. I like the idea.

Quick ascii mockup:

    EthnicCake

            Total       Wk1     Wk2     Wk3     Wk4     Wk5
    Set 5   250  8*     50 **   50 *    50 *    50 **   50 **
    Set 4   240 10*     40 **   50 **   50 **   50 **   50 **
    Set 3   250 10*     50 **   50 **   50 **   50 **   50 **
    Set 2   200  8*     50 **   --      50 **   50 **   50**
    Set 1   ??

Issues: How to handle bonus weeks? How to handle Set 1? (I could divide it into 3 subsets as per RoGGa's example.)

(RoGGa: If you want to make a fixed-with block, indent all the lines with 4 spaces.)

**Comment by alkemann** [comment]
<img width="468" alt="Screenshot 2019-11-25 at 14 31 21" src="https://user-images.githubusercontent.com/48854/69544616-60aed800-0f90-11ea-81fb-4fb3127a71d2.png">
Listing from first set to last set participating in, weeks 1-5. Non-scoring submissions (late and duplicates) as well as bonus weeks in the submission list below. 

Thoughts?
