### ISSUE TITLE
About page: recommended tiny changes

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#52]
1. Add: "whenever specified." at the en of this sentence:
"Challenges can be played in either the latest stable or trunk version, and occasionally other versions."

2.  for those playing offline, add a bit more detail for submitting a morgue...especially about PasteBin

3. have the conduct example for 3 milestones plus 2 conducts (15 + 7 = 22 pts)

**Comment by kitchen-ace** [comment]
Agreed with these, will do them tomorrow.
