### ISSUE TITLE
Add a countdown

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#53]
I just came across how to do a countdown and thought it might look cute:
https://www.w3schools.com/howto/howto_js_countdown.asp

**Comment by alkemann** [comment]
👎 in my opinion.

**Comment by kitchen-ace** [comment]
Also mine. I don't want to emphasize the "finality" of the deadline since in practice I accept runs that are late by a few days.
