### ISSUE TITLE
adjust scoring for no win and 2 stars

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#59]
Only 1 star is possible without a win...unless I missed something somewhere.

see: https://cdn.discordapp.com/attachments/558269304852709393/570951159418978324/moderate_submissions.png

**Comment by alkemann** [comment]
What is this issue asking for? Cases like this is why we have moderation right? This score is only presented to a moderator.

**Comment by RoGGa-loves-DCSS** [comment]
I guess my point is: the automated scoring should not allow 2 stars for a run without a win.

**Comment by kitchen-ace** [comment]
If scoring is going to be automated at some point, checking for a win can be done as part of checking for star eligibility. In fact I think it has to be, so having this as a sanity check shouldn't be needed imo.
