### ISSUE TITLE
A memo type field for a post-week write-up of noticeable mentions.

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#6]
FR: A memo type field that kitchen_ace (or someone else) can do a post-week write-up of noticeable mentions.

Something like for S4w2:
- TheMeInTeam has an ongoing 3-game streak with the DrGl CosPlay win as the middle game. Will he wait for the Set4Week3 combo to make it 4? ...me thinks not!
- NightWolf (Eldin) made it out of Abyss:3 with his DrGl^Qaz ...only to die in the Hall of Blades due to having used too many consumables in Abyss;
- RoGGa is still bragging about playing 10-20 games per week without winning; and
- lextramoth loves getting shafted!

**Comment by RoGGa-loves-DCSS** [comment]
ideally, graphics could be included such as Ge0ff's Set4W2:
https://cdn.discordapp.com/attachments/540799081283584012/559129616850223115/v5.png
with a text caption

**Comment by alkemann** [comment]
something like this isnt easy to get into the DB. I think it would be cool to pair this app with a blog app. the blog posts could have tags so you can easily know which challenge it is from and if it is from Ace or a participant.

**Comment by kitchen-ace** [comment]
Since I am planning to still use reddit for discussion threads etc, I don't think this is particularly necessary.  Linking to reddit comments is already close enough to a blog for me.
