### ISSUE TITLE
Make reddit use the character image as a thumbnail

### ISSUE THREAD

**Issue by kitchen-ace** [alkemann/stone_soup_cosplay#60]
`<meta property="og:image" content="_the imgur link for the challenge_.png" />`

Can default to current challenge's image for non-challenge-detail pages.

Something I read recommended using `og:image:url` property instead (or as well)

**Comment by kitchen-ace** [comment]
I've used a static image for now, for this week's challenge, but it doesn't appear to be working. Reddit caches thumbnails but I don't think that's the problem.

**Comment by alkemann** [comment]
I can use the same strategy as #61 to change the value in the meta tag based on challenge, but I guess we must find out why it doesnt work at all first?

**Comment by alkemann** [comment]
<img width="850" alt="Screenshot 2019-11-25 at 17 01 02" src="https://user-images.githubusercontent.com/48854/69556588-43d0cf80-0fa5-11ea-9555-8021b9369b36.png">

Yay it works now
