### ISSUE TITLE
last entry is cut off on http://www.crawlcosplay.com/history

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#67]
We've added new Uniques lately so now things are getting cut off

**Comment by RoGGa-loves-DCSS** [comment]
the same issue is happening on page: http://www.crawlcosplay.com/admin/challenges/list

**Comment by RoGGa-loves-DCSS** [comment]
the same is happening to page: http://www.crawlcosplay.com/admin/challenges/list

**Comment by alkemann** [comment]
What is getting cut off?

**Comment by RoGGa-loves-DCSS** [comment]
[](https://media.discordapp.net/attachments/558269304852709393/970451782625001482/unknown.png?width=888&height=473)

**Comment by RoGGa-loves-DCSS** [comment]
see Discord for screen capture

**Comment by alkemann** [comment]
Rogga's fix solved it.
